### ISSUE TITLE
dynamically update the title and meta for SEO

### ISSUE THREAD

**Issue by christianjosephvarriale** [christianjosephvarriale/Tekblg#22]
## Description
Currently, the metadata and title are the same for each page which is not favorable for SEO. Fix this by making it pull from the page

## Components

- [ ] Figure out what meta needs to be shown on each page

- [ ] Figure out how to display it on each page

- [ ] Add a meta field on the blog posts
